name: Task Monitor Bot

on:
  schedule:
    - cron: '*/15 * * * *' # Cứ 15 phút quét một lần (GitHub giới hạn tối thiểu 15p)
  workflow_dispatch:      # Cho phép bạn nhấn nút chạy thủ công bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credentials.json
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run Monitor Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python monitor.py
