name: Skybow Auto Report

on:
  schedule:
    - cron: '30 20 * * 1-5'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pandas requests streamlit st-gsheets-connection plotly
          
      - name: Tạo file Streamlit Secrets để kết nối Google Sheets
        run: |
          mkdir -p .streamlit
          cat <<EOF > .streamlit/secrets.toml
          [connections.gsheets]
          type = "service_account"
          project_id = "${{ secrets.GCP_PROJECT_ID }}"
          private_key_id = "${{ secrets.GCP_PRIVATE_KEY_ID }}"
          private_key = "${{ secrets.GCP_PRIVATE_KEY }}"
          client_email = "${{ secrets.GCP_CLIENT_EMAIL }}"
          client_id = "${{ secrets.GCP_CLIENT_ID }}"
          auth_uri = "https://accounts.google.com/o/oauth2/auth"
          token_uri = "https://oauth2.googleapis.com/token"
          auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
          client_x509_cert_url = "${{ secrets.GCP_CERT_URL }}"
          EOF
          
      - name: Run Report
        run: python app.py --action skybow
