name: Skybow Auto Report

on:
  schedule:
    - cron: '30 0 * * 1-5'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pandas requests streamlit st-gsheets-connection plotly
      - name: Run Report
        run: python app.py --action skybow
